---
abstract: 'Catalyst based application'
author:
  - 'Monsenhor, C<< <monsenhor@cpan.org> >>'
  - 'Monsenhor <monsenhor@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: YAC
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Action::RenderView: 0
  Catalyst::Authentication::Realm::SimpleDB: 0
  Catalyst::Plugin::Authentication: 0
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::Session: 0
  Catalyst::Plugin::Session::State::Cookie: 0
  Catalyst::Plugin::Session::Store::FastMmap: 0
  Catalyst::Plugin::StackTrace: 0
  Catalyst::Plugin::Static::Simple: 0
  Catalyst::Runtime: 5.80025
  Config::General: 0
  Image::Magick: 0
  Image::Size: 0
  JSON: 0
  Moose: 0
  PSGI: 0
  Path::Class: 0
  namespace::autoclean: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.21
